name: Build Rulu Installer

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-installer:
    runs-on: windows-latest

    steps:
      # Checkout the repository code (includes setup.nsi)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Create directory structure
      - name: Create directory structure
        run: |
          mkdir app
          mkdir assets
        shell: cmd

      # Download the latest rulu.exe from GitHub Releases
      - name: Download rulu.exe
        run: |
          curl -L -o app/rulu.exe https://github.com/NPSummers/Rulu/releases/download/ver-0.1.0-patch-1/rulu.exe
        shell: cmd

      # Install NSIS
      - name: Install NSIS
        run: |
          choco install nsis -y
        shell: cmd

      # Compile NSIS script
      - name: Compile NSIS installer
        run: |
          makensis installer/setup.nsi
        shell: cmd

      # Upload the installer as an artifact
      - name: Upload Rulu installer
        uses: actions/upload-artifact@v4
        with:
          name: Rulu_Setup
          path: Rulu_Setup.exe

      # Upload setup.nsi for debugging (optional)
      - name: Upload setup.nsi for debugging
        uses: actions/upload-artifact@v4
        with:
          name: setup-nsi
          path: setup.nsi
